;METADATA=(Diff=true, UseCommands=true)
[/Script/LevelSwitcher.LevelSwitcherSettings]
+FavoriteLevels=/Game/Maps/Proto02_Traversal
+FavoriteLevels=/Game/Maps/Proto03_Sub_HullPrecision
+FavoriteLevels=/Game/Maps/L_FP_GeneratorRun
+FavoriteLevels=/Game/Maps/L_WaterProto_Phase0
+FavoriteLevels=/Game/Maps/L_WaterProto_TwoRooms
StartupLevel=/Game/Maps/Proto03_Sub_HullPrecision

