;METADATA=(Diff=true, UseCommands=true)
[/Script/LevelSwitcher.LevelSwitcherSettings]
+FavoriteLevels=/Game/Blueprint/LVL_Sub
+FavoriteLevels=/Game/Maps/Proto02_Traversal
+FavoriteLevels=/Game/Maps/Proto03_Sub_HullPrecision
StartupLevel=/Game/Maps/Proto03_Sub_HullPrecision

