;METADATA=(Diff=true, UseCommands=true)
[/Script/LevelSwitcher.LevelSwitcherSettings]
+FavoriteLevels=/Game/Maps/Proto02_Traversal
+FavoriteLevels=/Game/Maps/Proto03_Sub_HullPrecision
+FavoriteLevels=/Game/Maps/L_FP_GeneratorRun
StartupLevel=/Game/Maps/Proto03_Sub_HullPrecision

