#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "SubmarineGeneratorEnvelopeDef.generated.h"

UENUM(BlueprintType)
enum class EGenBowSternProfile : uint8
{
	Rounded UMETA(DisplayName = "Rounded"),
	Needle  UMETA(DisplayName = "Needle"),
	Blunt   UMETA(DisplayName = "Blunt"),
	Bulbous UMETA(DisplayName = "Bulbous"),
	Tapered UMETA(DisplayName = "Tapered")
};

/**
 * Hull envelope input for the submarine generator pipeline.
 * Contains only the fields actually consumed by USubmarineGenerator and
 * USubmarineMeshBuilder: spine length, radius profile, cross-section shape,
 * bow/stern taper, and exterior hull offset.
 *
 * The legacy USubmarineEnvelopeDef in SubCompiler/ is unrelated and will be
 * removed with the rest of the SubCompiler legacy in Phase 7B.
 */
UCLASS(BlueprintType)
class SUB3D_API USubmarineGeneratorEnvelopeDef : public UDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope", meta = (ClampMin = "500.0"))
	float SpineLengthCm = 1520.f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope", meta = (ClampMin = "50.0"))
	float DefaultRadiusCm = 180.f;

	// Distance in cm between the interior wall and the exterior hull surface.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|Exterior", meta = (ClampMin = "0.0", ClampMax = "50.0"))
	float ExteriorHullOffsetCm = 12.f;

	// Superellipse exponent for cross-section shape.
	// 2.0 = circle/ellipse, >2 = squarish, <2 = diamond/organic.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|Section", meta = (ClampMin = "0.5", ClampMax = "8.0"))
	float SectionExponent = 2.f;

	// Width-to-height ratio of the cross-section.
	// 1.0 = symmetric, >1 = wider than tall, <1 = taller than wide.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|Section", meta = (ClampMin = "0.5", ClampMax = "2.0"))
	float WidthToHeightRatio = 1.f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern")
	EGenBowSternProfile BowProfile = EGenBowSternProfile::Rounded;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern")
	EGenBowSternProfile SternProfile = EGenBowSternProfile::Tapered;

	// Length of the bow taper zone as fraction of SpineLength.
	// Only used as a weight to split the remaining spine between bow and stern.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern", meta = (ClampMin = "0.0", ClampMax = "0.4"))
	float BowTaperFraction = 0.12f;

	// Length of the stern taper zone as fraction of SpineLength.
	// Only used as a weight to split the remaining spine between bow and stern.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern", meta = (ClampMin = "0.0", ClampMax = "0.4"))
	float SternTaperFraction = 0.15f;

	// Explicit length of the bow cap zone in centimeters. Controls the
	// geometry extending beyond the first hull compartment in BuildExteriorHull.
	// Does not affect EvaluateRadius.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern", meta = (ClampMin = "0.0", ClampMax = "2000.0"))
	float BowCapLengthCm = 240.f;

	// Explicit length of the stern cap zone in centimeters. Controls the
	// geometry extending beyond the last hull compartment in BuildExteriorHull.
	// Does not affect EvaluateRadius.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern", meta = (ClampMin = "0.0", ClampMax = "2000.0"))
	float SternCapLengthCm = 320.f;

	// Decay exponent for the bow profile. 1.0 = default profile shape,
	// >1 = sharper (radius stays small longer), <1 = rounder.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern", meta = (ClampMin = "0.1", ClampMax = "4.0"))
	float BowSharpness = 1.f;

	// Decay exponent for the stern profile. 1.0 = default profile shape,
	// >1 = sharper (radius stays small longer), <1 = rounder.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern", meta = (ClampMin = "0.1", ClampMax = "4.0"))
	float SternSharpness = 1.f;

	// Fraction of the spine occupied by the parallel body (constant radius)
	// between the bow and stern taper zones. Authoritative length control.
	// 0.55 = 55% body + 45% split between bow and stern tapers.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern", meta = (ClampMin = "0.1", ClampMax = "0.9"))
	float BodyLengthFraction = 0.55f;

	// Number of control rings generated by the GeneratorEditor. Reserved
	// for Phase 2 tooling; not consumed by the current mesh builder.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Envelope|BowStern", meta = (ClampMin = "5", ClampMax = "17"))
	int32 ControlRingCount = 9;

	UFUNCTION(BlueprintPure, Category = "Envelope")
	float EvaluateRadius(float NormalizedPosition) const;

	UFUNCTION(BlueprintPure, Category = "Envelope")
	float EvaluateBowSternTaper(float NormalizedPosition) const;

	/**
	 * Returns a radius multiplier in [0, 1] for a cap profile.
	 * T is "normalized distance from tip toward body":
	 *   - T=0 at the tip (zero radius)
	 *   - T=1 at the body boundary (full radius)
	 * Shared between EvaluateRadius, EvaluateBowSternTaper, and BuildExteriorHull
	 * so the cap geometry matches the analytical radius profile.
	 */
	static float ApplyCapProfile(EGenBowSternProfile Profile, float T, float Sharpness);

	/**
	 * Returns the normalized body boundaries [BodyStart, BodyEnd] as computed
	 * from BodyLengthFraction and the bow/stern taper weights. Within this
	 * range EvaluateRadius returns DefaultRadiusCm; outside it returns the
	 * tapered cap profile. Used by SubmarineGenerator::DeriveCompartments to
	 * place compartments in the constant-radius body region.
	 */
	UFUNCTION(BlueprintPure, Category = "Envelope")
	void GetBodyBounds(float& OutBodyStart, float& OutBodyEnd) const;

	// Returns the half-width of the hull interior at a given local radius and
	// vertical offset from the section center. Uses SectionExponent and
	// WidthToHeightRatio. Returns 0 if the offset is at or beyond the boundary.
	UFUNCTION(BlueprintPure, Category = "Envelope")
	float EvaluateSectionHalfWidth(float LocalRadius, float VerticalOffset) const;

	// Evaluates a point on the superellipse arc at a given angle.
	UFUNCTION(BlueprintCallable, Category = "Envelope")
	void EvaluateSectionPoint(float LocalRadius, float Angle, FVector2D& OutPosition, FVector2D& OutInwardNormal) const;

	// Numerical approximation of the superellipse arc length between two angles.
	UFUNCTION(BlueprintPure, Category = "Envelope")
	float GetSectionArcLength(float LocalRadius, float StartAngle, float EndAngle, int32 Samples = 16) const;
};
